env:
    rclone_config: "ENCRYPTED[fb2a09ad0b21f52faf35d6861c34c40311f9a48ed369ae5dd82a2ccfeb8bd5b74bc3b0dbf4d0a8f34c8cb1b511c4b68a]"

task:
    name: cirrus
    timeout_in: 120m
    container:
      image: inok2341/anu:latest
      cpu: 8
      memory: 32G      

    mengdownload_script:
      - bash mengdownload
    mengsinkronisasi_script:
      - ./sinkronisasi
    membuat_akhir_script:
      - bash membuat_akhir
    mengunggah_script:
      - ./mengunggah
