#!/bin/bash

sudo apt install wget
sudo apt install python2 -y
git config --global  user.name "l3773"
git config --global  user.email "l3773683@gmail.com"
cd /tmp/rom

repo init -q --no-repo-verify --depth=1 -u https://github.com/AospExtended/manifest -b 11.x -g default,-device,-mips,-darwin,-notdefault
git clone https://github.com/l3773/local_manifests .repo/local_manifests
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all)

# apply patch
cd frameworks/base &&  wget https://github.com/PixelExperience/frameworks_base/commit/37f5a323245b0fd6269752742a2eb7aa3cae24a7.patch && git apply 37f5a323245b0fd6269752742a2eb7aa3cae24a7.patch
cd -
cd frameworks/opt/net/ims &&  wget https://github.com/PixelExperience/frameworks_opt_net_ims/commit/661ae9749b5ea7959aa913f2264dc5e170c63a0a.patch && git apply 661ae9749b5ea7959aa913f2264dc5e170c63a0a.patch
cd -
cd frameworks/opt/net/wifi &&  wget https://github.com/PixelExperience/frameworks_opt_net_wifi/commit/3bd2c14fbda9c079a4dc39ff4601ba54da589609.patch && git apply 3bd2c14fbda9c079a4dc39ff4601ba54da589609.patch
cd -
cd frameworks/base && rm -rf *patch && curl -L -o patch4.patch https://dl.uploadgram.me/60a9c138305adh?raw
patch -p1 < patch4.patch 
cd -
